### ISSUE TITLE
Arkplayz Cant View dashboard

### ISSUE THREAD

**Issue by ArkplayzYT** [typicalninja493/axix-chatbot#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Hello and I am Axix Bot mod and I WANNA SEE THE DASH BOARD AHHHHHHHHHHHH

**Comment by typicalninja493** [comment]
umm you just used the template and didn't fill the blanks also the dashboard is still not released yet
